stages:
  - name: Publish
    steps:
      - publishImageConfig:
          dockerFilePath: ./Dockerfile
          buildContext: .
          tag: example-ci:${CICD_EXECUTION_SEQUENCE}
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
