apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-pipeline-ci
  labels:
    app: rancher-pipeline-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-pipeline-ci
  template:
    metadata:
      labels:
        app: rancher-pipeline-ci
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: rancher-pipeline-ci
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
